export const SNACKS_MENU_REQUEST = 'SNACKS_MENU_REQUEST';
export const SNACKS_MENU_SUCCESS = 'SNACKS_MENU_SUCCESS';
export const SNACKS_MENU_FAIL = 'SNACKS_MENU_FAIL';

export const APPETIZER_MENU_REQUEST = 'APPETIZER_MENU_REQUEST';
export const APPETIZER_MENU_SUCCESS = 'APPETIZER_MENU_SUCCESS';
export const APPETIZER_MENU_FAIL = 'APPETIZER_MENU_FAIL';

export const MAINMENU_MENU_REQUEST = 'MAINMENU_MENU_REQUEST';
export const MAINMENU_MENU_SUCCESS = 'MAINMENU_MENU_SUCCESS';
export const MAINMENU_MENU_FAIL = 'MAINMENU_MENU_FAIL';

export const PIZZA_MENU_REQUEST = 'PIZZA_MENU_REQUEST';
export const PIZZA_MENU_SUCCESS = 'PIZZA_MENU_SUCCESS';
export const PIZZA_MENU_FAIL = 'PIZZA_MENU_FAIL';

export const DESSERT_MENU_REQUEST = 'DESSERT_MENU_REQUEST';
export const DESSERT_MENU_SUCCESS = 'DESSERT_MENU_SUCCESS';
export const DESSERT_MENU_FAIL = 'DESSERT_MENU_FAIL';

export const BURGER_MENU_REQUEST = 'BURGER_MENU_REQUEST';
export const BURGER_MENU_SUCCESS = 'BURGER_MENU_SUCCESS';
export const BURGER_MENU_FAIL = 'BURGER_MENU_FAIL';

export const SEAFOOD_MENU_REQUEST = 'SEAFOOD_MENU_REQUEST';
export const SEAFOOD_MENU_SUCCESS = 'SEAFOOD_MENU_SUCCESS';
export const SEAFOOD_MENU_FAIL = 'SEAFOOD_MENU_FAIL';

export const COCKTAIL_MENU_REQUEST = 'COCKTAIL_MENU_REQUEST';
export const COCKTAIL_MENU_SUCCESS = 'COCKTAIL_MENU_SUCCESS';
export const COCKTAIL_MENU_FAIL = 'COCKTAIL_MENU_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL';